name: Stable Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    uses: Conduction/.github/.forgejo/workflows/release-semrel.yml@main
    with:
      app-name: nldesign
      release-branch: master
    secrets: inherit
