var classes = [
    {
        "name": "OCA\\NLDesign\\Controller\\HealthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\Server",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 48,
        "vocabulary": 24,
        "volume": 220.08,
        "difficulty": 4.74,
        "effort": 1042.48,
        "level": 0.21,
        "bugs": 0.07,
        "time": 58,
        "intelligentContent": 46.46,
        "number_operators": 12,
        "number_operands": 36,
        "number_operators_unique": 5,
        "number_operands_unique": 19,
        "cloc": 21,
        "loc": 48,
        "lloc": 27,
        "mi": 94.7,
        "mIwoC": 51.97,
        "commentWeight": 42.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "OCA\\NLDesign\\Controller\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Controller\\SettingsController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAvailableTokenSets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveBooleanSetting",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setSloganSetting",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setMenuLabelsSetting",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateThemingValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getThemingValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildThemingSnapshot",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOverrides",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setOverrides",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exportOverrides",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "importOverrides",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateUploadedFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseCssDeclarations",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filterEditableTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokenSetPreview",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 18,
        "nbMethods": 18,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 37,
        "ccn": 20,
        "ccnMethodMax": 5,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\IConfig",
            "OCA\\NLDesign\\Service\\TokenSetService",
            "OCA\\NLDesign\\Service\\ThemingService",
            "OCA\\NLDesign\\Service\\CustomOverridesService",
            "OCA\\NLDesign\\Service\\TokenSetPreviewService",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCA\\NLDesign\\Service\\TokenRegistry",
            "OCA\\NLDesign\\Service\\TokenRegistry",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\DataDownloadResponse",
            "OCP\\AppFramework\\Http\\DataDownloadResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCA\\NLDesign\\Service\\TokenRegistry",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 352,
        "vocabulary": 93,
        "volume": 2301.78,
        "difficulty": 15.48,
        "effort": 35636.05,
        "level": 0.06,
        "bugs": 0.77,
        "time": 1980,
        "intelligentContent": 148.68,
        "number_operators": 95,
        "number_operands": 257,
        "number_operators_unique": 10,
        "number_operands_unique": 83,
        "cloc": 196,
        "loc": 367,
        "lloc": 171,
        "mi": 70.32,
        "mIwoC": 25.06,
        "commentWeight": 45.27,
        "kanDefect": 1.45,
        "relativeStructuralComplexity": 729,
        "relativeDataComplexity": 1.07,
        "relativeSystemComplexity": 730.07,
        "totalStructuralComplexity": 13122,
        "totalDataComplexity": 19.18,
        "totalSystemComplexity": 13141.18,
        "package": "OCA\\NLDesign\\Controller\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Controller\\MetricsController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "collectTokenSetMetrics",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "collectOverrideMetrics",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\IConfig",
            "OCA\\NLDesign\\Service\\TokenSetService",
            "OCA\\NLDesign\\Service\\CustomOverridesService",
            "Psr\\Log\\LoggerInterface",
            "OCP\\AppFramework\\Http\\TextPlainResponse",
            "OCP\\AppFramework\\Http\\TextPlainResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 171,
        "vocabulary": 61,
        "volume": 1014.16,
        "difficulty": 4.21,
        "effort": 4270.13,
        "level": 0.24,
        "bugs": 0.34,
        "time": 237,
        "intelligentContent": 240.86,
        "number_operators": 51,
        "number_operands": 120,
        "number_operators_unique": 4,
        "number_operands_unique": 57,
        "cloc": 44,
        "loc": 109,
        "lloc": 65,
        "mi": 80.64,
        "mIwoC": 39,
        "commentWeight": 41.64,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 100.27,
        "totalStructuralComplexity": 400,
        "totalDataComplexity": 1.09,
        "totalSystemComplexity": 401.09,
        "package": "OCA\\NLDesign\\Controller\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\AppInfo\\Application",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "injectThemeCSS",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "OCP\\AppFramework\\App",
            "OCP\\AppFramework\\Bootstrap\\IBootstrap",
            "OCP\\AppFramework\\Bootstrap\\IRegistrationContext",
            "OCP\\AppFramework\\Bootstrap\\IBootContext",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCA\\NLDesign\\Service\\CustomOverridesService",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util"
        ],
        "parents": [
            "OCP\\AppFramework\\App"
        ],
        "implements": [
            "OCP\\AppFramework\\Bootstrap\\IBootstrap"
        ],
        "lcom": 3,
        "length": 56,
        "vocabulary": 30,
        "volume": 274.79,
        "difficulty": 3.23,
        "effort": 887.77,
        "level": 0.31,
        "bugs": 0.09,
        "time": 49,
        "intelligentContent": 85.05,
        "number_operators": 14,
        "number_operands": 42,
        "number_operators_unique": 4,
        "number_operands_unique": 26,
        "cloc": 46,
        "loc": 87,
        "lloc": 41,
        "mi": 92.48,
        "mIwoC": 47.34,
        "commentWeight": 45.15,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 64.08,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 256.33,
        "package": "OCA\\NLDesign\\AppInfo\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\ThemingService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValidHexColor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateImagePaths",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateSinglePath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyImages",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImageManager",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 20,
        "ccnMethodMax": 6,
        "externals": [
            "OCA\\Theming\\ImageManager",
            "OCA\\Theming\\ThemingDefaults",
            "OCP\\App\\IAppManager",
            "OCA\\Theming\\ImageManager"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 188,
        "vocabulary": 44,
        "volume": 1026.37,
        "difficulty": 14,
        "effort": 14369.22,
        "level": 0.07,
        "bugs": 0.34,
        "time": 798,
        "intelligentContent": 73.31,
        "number_operators": 62,
        "number_operands": 126,
        "number_operators_unique": 8,
        "number_operands_unique": 36,
        "cloc": 84,
        "loc": 171,
        "lloc": 87,
        "mi": 78.15,
        "mIwoC": 33.92,
        "commentWeight": 44.23,
        "kanDefect": 1.7,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.21,
        "relativeSystemComplexity": 27.21,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 17.67,
        "totalSystemComplexity": 217.67,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenSetService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAppPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAvailableTokenSets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValidTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "readManifest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formatName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 20,
        "ccn": 16,
        "ccnMethodMax": 9,
        "externals": [
            "OCP\\App\\IAppManager"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 153,
        "vocabulary": 41,
        "volume": 819.71,
        "difficulty": 11.76,
        "effort": 9637.75,
        "level": 0.09,
        "bugs": 0.27,
        "time": 535,
        "intelligentContent": 69.72,
        "number_operators": 56,
        "number_operands": 97,
        "number_operators_unique": 8,
        "number_operands_unique": 33,
        "cloc": 59,
        "loc": 130,
        "lloc": 71,
        "mi": 80.28,
        "mIwoC": 37.06,
        "commentWeight": 43.21,
        "kanDefect": 1.17,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.42,
        "relativeSystemComplexity": 11.42,
        "totalStructuralComplexity": 54,
        "totalDataComplexity": 14.5,
        "totalSystemComplexity": 68.5,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.13,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenSetPreviewService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResolvedColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseCssVars",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseMappings",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resolveVarReference",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 17,
        "ccn": 14,
        "ccnMethodMax": 5,
        "externals": [
            "OCP\\App\\IAppManager",
            "OCA\\NLDesign\\Service\\TokenRegistry"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 160,
        "vocabulary": 37,
        "volume": 833.51,
        "difficulty": 10.06,
        "effort": 8388.9,
        "level": 0.1,
        "bugs": 0.28,
        "time": 466,
        "intelligentContent": 82.82,
        "number_operators": 56,
        "number_operands": 104,
        "number_operators_unique": 6,
        "number_operands_unique": 31,
        "cloc": 76,
        "loc": 154,
        "lloc": 78,
        "mi": 80.68,
        "mIwoC": 36.39,
        "commentWeight": 44.29,
        "kanDefect": 1.47,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.87,
        "relativeSystemComplexity": 26.87,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 9.33,
        "totalSystemComplexity": 134.33,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\CustomOverridesService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFilePath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureExists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filterEditable",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "writeFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "atomicRename",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildCss",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildDeclarationLines",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseDeclarations",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRawContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 11,
        "nbMethodsPrivate": 7,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 25,
        "ccn": 15,
        "ccnMethodMax": 3,
        "externals": [
            "OCP\\App\\IAppManager",
            "OCA\\NLDesign\\Service\\TokenRegistry",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 199,
        "vocabulary": 47,
        "volume": 1105.36,
        "difficulty": 9,
        "effort": 9948.27,
        "level": 0.11,
        "bugs": 0.37,
        "time": 553,
        "intelligentContent": 122.82,
        "number_operators": 76,
        "number_operands": 123,
        "number_operators_unique": 6,
        "number_operands_unique": 41,
        "cloc": 125,
        "loc": 237,
        "lloc": 113,
        "mi": 77,
        "mIwoC": 31.89,
        "commentWeight": 45.12,
        "kanDefect": 1.61,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 1.48,
        "relativeSystemComplexity": 82.48,
        "totalStructuralComplexity": 972,
        "totalDataComplexity": 17.7,
        "totalSystemComplexity": 989.7,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.11,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenRegistry",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTokens",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLoginTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContentTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatusTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTypographyTokens",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTabLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokenNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEditable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokensByTab",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 9,
        "length": 394,
        "vocabulary": 123,
        "volume": 2735.35,
        "difficulty": 3.17,
        "effort": 8658.18,
        "level": 0.32,
        "bugs": 0.91,
        "time": 481,
        "intelligentContent": 864.17,
        "number_operators": 11,
        "number_operands": 383,
        "number_operators_unique": 2,
        "number_operands_unique": 121,
        "cloc": 85,
        "loc": 129,
        "lloc": 44,
        "mi": 87.38,
        "mIwoC": 39.81,
        "commentWeight": 47.57,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.52,
        "relativeSystemComplexity": 26.52,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 13.67,
        "totalSystemComplexity": 238.67,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.3,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Settings\\Admin",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Settings\\ISettings",
            "OCP\\IConfig",
            "OCP\\IL10N",
            "OCA\\NLDesign\\Service\\TokenSetService",
            "OCP\\AppFramework\\Http\\TemplateResponse",
            "OCP\\AppFramework\\Http\\TemplateResponse"
        ],
        "parents": [],
        "implements": [
            "OCP\\Settings\\ISettings"
        ],
        "lcom": 3,
        "length": 48,
        "vocabulary": 20,
        "volume": 207.45,
        "difficulty": 3.18,
        "effort": 658.97,
        "level": 0.31,
        "bugs": 0.07,
        "time": 37,
        "intelligentContent": 65.31,
        "number_operators": 12,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 17,
        "cloc": 47,
        "loc": 76,
        "lloc": 29,
        "mi": 98.67,
        "mIwoC": 51.74,
        "commentWeight": 46.93,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 5.25,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 21,
        "package": "OCA\\NLDesign\\Settings\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    }
]