#!/usr/bin/env node
/**
 * Build script for NL Design System Icons
 *
 * Materializes the EUPL-compatible NL-government icon packs bundled in
 * @conduction/nextcloud-vue (src/icons/{rvo,openGemeenten,denHaag}.js — data-URI
 * catalogue modules, auto-generated by nextcloud-vue's scripts/generate-nl-icons.mjs)
 * into standalone SVG files under img/icons/{set}/{key}.svg.
 *
 * @conduction/nextcloud-vue is a devDependency consumed ONLY by this build script —
 * nothing under js/ or lib/ imports it; nldesign remains a no-Vue app and ships no
 * runtime JS dependency on nc-vue.
 *
 * This script does NOT copy anything from the proprietary Amsterdam Design System icon
 * package (that dependency is removed — see CHANGELOG.md) and does NOT touch img/logos/ —
 * the 23 organisation logos are static, checked-in huisstijl assets, not build output
 * (see img/ICONS.md).
 *
 * For exactly one release, a curated alias map (scripts/icon-aliases.json) additionally
 * writes replacement artwork under legacy Amsterdam PascalCase filenames at the
 * top-level img/icons/{Name}.svg, so URLs stored by consumers before this change
 * (e.g. launchpad tile data) keep resolving — always to EUPL-compatible replacement
 * bytes, never to Amsterdam artwork. Unmapped legacy names simply 404. See
 * scripts/icon-aliases.json and img/ICONS.md for the removal deadline.
 */

const fs = require('fs');
const path = require('path');

const iconsDestPath = path.join(__dirname, '..', 'img', 'icons');
const logosDestPath = path.join(__dirname, '..', 'img', 'logos');
const iconsMdPath = path.join(__dirname, '..', 'img', 'ICONS.md');
const aliasesPath = path.join(__dirname, 'icon-aliases.json');

/** Pack module -> destination set directory name. */
const PACKS = [
	{ specifier: '@conduction/nextcloud-vue/src/icons/rvo.js', exportName: 'rvoIcons', set: 'rvo', upstream: 'RVO / ROOS (Rijksdienst voor Ondernemend Nederland)', licence: 'CC0-1.0' },
	{ specifier: '@conduction/nextcloud-vue/src/icons/openGemeenten.js', exportName: 'openGemeentenIcons', set: 'open-gemeenten', upstream: 'OpenGemeenten Iconenset ("Line" style)', licence: 'CC0-1.0' },
	{ specifier: '@conduction/nextcloud-vue/src/icons/denHaag.js', exportName: 'denHaagIcons', set: 'den-haag', upstream: 'Gemeente Den Haag icon set', licence: 'EUPL-1.2' },
];

const DATA_URI_PREFIX = 'data:image/svg+xml,';

/**
 * Decode a nc-vue pack entry's data:image/svg+xml,... URI back into raw SVG markup.
 * The generator (nextcloud-vue/scripts/generate-nl-icons.mjs) encodes with a plain
 * encodeURIComponent (plus a few characters decoded back for readability), so a plain
 * decodeURIComponent is an exact inverse.
 */
function decodeDataUri(url) {
	if (!url.startsWith(DATA_URI_PREFIX)) {
		throw new Error(`Unexpected icon URL format (missing ${DATA_URI_PREFIX} prefix): ${url.slice(0, 40)}...`);
	}
	return decodeURIComponent(url.slice(DATA_URI_PREFIX.length));
}

/** Recreate a directory empty (idempotent regenerate). */
function resetDir(dir) {
	fs.rmSync(dir, { recursive: true, force: true });
	fs.mkdirSync(dir, { recursive: true });
}

async function main() {
	console.log('Building NL Design System Icons from @conduction/nextcloud-vue...');

	resetDir(iconsDestPath);

	/** @type {Map<string, { icons: Array<{id: string, label: string, url: string}>, upstream: string, licence: string }>} */
	const packData = new Map();
	/** @type {Map<string, string>} set/key -> decoded SVG content, for alias resolution */
	const svgByPath = new Map();

	for (const pack of PACKS) {
		const mod = await import(pack.specifier);
		const icons = mod[pack.exportName];
		if (!Array.isArray(icons) || icons.length === 0) {
			console.error(`✗ Pack "${pack.set}" (${pack.specifier}) yielded zero icons.`);
			process.exit(1);
		}

		const setDir = path.join(iconsDestPath, pack.set);
		fs.mkdirSync(setDir, { recursive: true });

		for (const entry of icons) {
			const svg = decodeDataUri(entry.url);
			const destFile = path.join(setDir, `${entry.id}.svg`);
			fs.writeFileSync(destFile, svg);
			svgByPath.set(`${pack.set}/${entry.id}`, svg);
		}

		packData.set(pack.set, { icons, upstream: pack.upstream, licence: pack.licence });
		console.log(`✓ Materialized ${icons.length} icons for set "${pack.set}" -> ${setDir}`);
	}

	// Legacy Amsterdam filename aliases (one-release deprecation shim).
	const aliasesRaw = JSON.parse(fs.readFileSync(aliasesPath, 'utf8'));
	const aliases = Object.fromEntries(
		Object.entries(aliasesRaw).filter(([key]) => key !== '_comment')
	);

	let aliasCount = 0;
	for (const [legacyName, replacementPath] of Object.entries(aliases)) {
		const svg = svgByPath.get(replacementPath);
		if (svg === undefined) {
			console.error(`✗ scripts/icon-aliases.json maps "${legacyName}" to unknown replacement "${replacementPath}".`);
			process.exit(1);
		}
		fs.writeFileSync(path.join(iconsDestPath, `${legacyName}.svg`), svg);
		aliasCount++;
	}
	console.log(`✓ Materialized ${aliasCount} legacy-name alias files (one-release deprecation shim)`);

	// img/logos/ is a static, checked-in directory — never created, modified, or written here.
	const logoCount = fs.existsSync(logosDestPath)
		? fs.readdirSync(logosDestPath).filter((f) => f.endsWith('.svg')).length
		: 0;

	writeIconsMd({ packData, aliases, logoCount });
	console.log(`✓ Regenerated ${iconsMdPath}`);

	const totalIcons = [...packData.values()].reduce((sum, p) => sum + p.icons.length, 0);
	console.log(`\n✅ Icon build complete! ${totalIcons} icons across ${packData.size} sets + ${aliasCount} legacy aliases + ${logoCount} logos (untouched).`);
}

/**
 * Regenerate img/ICONS.md: per-set inventories with licence/upstream attribution,
 * the legacy-alias table with its removal deadline, the PHP usage snippet, the
 * availability/fallback + naming-stability sections, and a Logos section.
 */
function writeIconsMd({ packData, aliases, logoCount }) {
	const setSections = [...packData.entries()].map(([set, data]) => {
		const sample = data.icons.slice(0, 20).map((i) => `- ${set}/${i.id}`).join('\n');
		const more = data.icons.length > 20 ? `\n... and ${data.icons.length - 20} more` : '';
		return `### ${set} (${data.icons.length} icons)

Upstream: ${data.upstream}
Licence: **${data.licence}**
Available in: \`img/icons/${set}/\`

${sample}${more}`;
	}).join('\n\n');

	const aliasRows = Object.entries(aliases)
		.map(([legacy, replacement]) => `| \`${legacy}.svg\` | \`${replacement}.svg\` |`)
		.join('\n');

	const logoFiles = fs.existsSync(logosDestPath)
		? fs.readdirSync(logosDestPath).filter((f) => f.endsWith('.svg')).map((f) => f.replace('.svg', ''))
		: [];

	const content = `# NL-Government Icons & Logos

This directory contains SVG icons materialized from the EUPL-compatible NL-government
icon packs bundled in \`@conduction/nextcloud-vue\` (\`src/icons/{rvo,openGemeenten,denHaag}.js\`),
plus the organisation logos in \`img/logos/\`.

**The proprietary City-of-Amsterdam icon set (\`@amsterdam/design-system-assets\`) is NOT
bundled.** Its \`LICENSE.md\` marks the set proprietary to the City of Amsterdam ("The
open-source licence does NOT apply to files in this directory"), restricted to contexts
where Amsterdam is the main communicator — redistributing it to arbitrary Dutch-government
Nextcloud instances is exactly the use its notice forbids. It was removed from this app;
see CHANGELOG.md for the full list of removed filenames and their replacements.

## Icons

${setSections}

## Licence attribution

Canonical licence record: \`@conduction/nextcloud-vue\`'s
\`src/icons/ATTRIBUTION.md\` (https://codeberg.org/Conduction/nextcloud-vue/src/branch/main/src/icons/ATTRIBUTION.md).

| Set | Upstream | Licence |
| --- | --- | --- |
${[...packData.entries()].map(([set, data]) => `| \`${set}\` | ${data.upstream} | **${data.licence}** |`).join('\n')}

## Legacy Amsterdam filename aliases (one-release deprecation)

For exactly **one release**, the legacy Amsterdam Design System filenames listed below
resolve to a top-level \`img/icons/{Name}.svg\` file — a byte-identical copy of the mapped
replacement artwork below, never Amsterdam artwork. **These aliases are removed in the
next minor release** (\`scripts/icon-aliases.json\` emptied, the build stops emitting
top-level files). Any legacy name NOT in this table returns HTTP 404 today; see
CHANGELOG.md for the full list of names removed without a replacement.

| Legacy path (deprecated) | Replacement artwork |
| --- | --- |
${aliasRows}

## Usage in Nextcloud

\`\`\`php
// In your template or controller
<img src="<?php p(\\OC::$server->getURLGenerator()->imagePath('nldesign', 'icons/rvo/rvo-zoek.svg')); ?>" alt="Search">
\`\`\`

Vue-based consumers SHOULD prefer importing the packs from \`@conduction/nextcloud-vue\`
directly (e.g. \`CnIconBrowser\` \`url-icons\`); the \`imagePath\` contract above exists for
PHP/template and other non-Vue consumers.

These URLs only resolve while the nldesign app is enabled. Consumers must ship a fallback
icon or declare a dependency on \`nldesign\`.

## Logos (${logoCount} total)

Available in: \`img/logos/\`. Static, checked-in huisstijl assets tied to token sets
(\`token-sets.json\` \`theming.logo\` entries) — organisation marks displayed as that
organisation's own identity on that organisation's own instance. **Not build output**:
\`scripts/build-icons.js\` never creates, modifies, or deletes anything under \`img/logos/\`.

${logoFiles.map((f) => `- ${f}`).join('\n')}

## Naming stability (public API)

Icon and logo filenames are a public API consumed by other apps. Within an installed
nc-vue pack version, renaming or removing a bundled icon or logo is a **breaking change**:
record it in the changelog (old + new name) and regenerate this file in the same change so
the inventory regression test (\`tests/Unit/IconAssetsTest.php\`) keeps passing. Upgrading
the \`@conduction/nextcloud-vue\` dependency (which can change pack contents) MUST be an
explicit, reviewed change whose diff of added/removed keys is listed in the changelog —
never a silent regenerate. Removing the legacy Amsterdam aliases at the end of the
deprecation window is a planned, pre-announced break that references the release that
announced it.
`;

	fs.writeFileSync(iconsMdPath, content);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
