var classes = [
    {
        "name": "OCA\\NLDesign\\Controller\\SettingsController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setSloganSetting",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setMenuLabelsSetting",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\IConfig",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 76,
        "vocabulary": 28,
        "volume": 365.36,
        "difficulty": 4.83,
        "effort": 1765.9,
        "level": 0.21,
        "bugs": 0.12,
        "time": 98,
        "intelligentContent": 75.59,
        "number_operators": 18,
        "number_operands": 58,
        "number_operators_unique": 4,
        "number_operands_unique": 24,
        "cloc": 56,
        "loc": 98,
        "lloc": 42,
        "mi": 92.17,
        "mIwoC": 46.11,
        "commentWeight": 46.06,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.55,
        "relativeSystemComplexity": 10.55,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7.75,
        "totalSystemComplexity": 52.75,
        "package": "OCA\\NLDesign\\Controller\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\AppInfo\\Application",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "injectThemeCSS",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "OCP\\AppFramework\\App",
            "OCP\\AppFramework\\Bootstrap\\IBootstrap",
            "OCP\\AppFramework\\Bootstrap\\IRegistrationContext",
            "OCP\\AppFramework\\Bootstrap\\IBootContext",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util",
            "OCP\\Util"
        ],
        "parents": [
            "OCP\\AppFramework\\App"
        ],
        "implements": [
            "OCP\\AppFramework\\Bootstrap\\IBootstrap"
        ],
        "lcom": 3,
        "length": 45,
        "vocabulary": 24,
        "volume": 206.32,
        "difficulty": 3.3,
        "effort": 680.87,
        "level": 0.3,
        "bugs": 0.07,
        "time": 38,
        "intelligentContent": 62.52,
        "number_operators": 12,
        "number_operands": 33,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 42,
        "loc": 76,
        "lloc": 34,
        "mi": 95.65,
        "mIwoC": 49.98,
        "commentWeight": 45.67,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 36.11,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 0.43,
        "totalSystemComplexity": 144.43,
        "package": "OCA\\NLDesign\\AppInfo\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\ThemingService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValidHexColor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateImagePaths",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateSinglePath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyImages",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImageManager",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 20,
        "ccnMethodMax": 6,
        "externals": [
            "OCA\\Theming\\ImageManager",
            "OCA\\Theming\\ThemingDefaults",
            "OCP\\App\\IAppManager",
            "OCA\\Theming\\ImageManager"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 188,
        "vocabulary": 44,
        "volume": 1026.37,
        "difficulty": 14,
        "effort": 14369.22,
        "level": 0.07,
        "bugs": 0.34,
        "time": 798,
        "intelligentContent": 73.31,
        "number_operators": 62,
        "number_operands": 126,
        "number_operators_unique": 8,
        "number_operands_unique": 36,
        "cloc": 84,
        "loc": 171,
        "lloc": 87,
        "mi": 78.15,
        "mIwoC": 33.92,
        "commentWeight": 44.23,
        "kanDefect": 1.7,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.21,
        "relativeSystemComplexity": 27.21,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 17.67,
        "totalSystemComplexity": 217.67,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenSetService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAppPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAvailableTokenSets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValidTokenSet",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "readManifest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formatName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 20,
        "ccn": 16,
        "ccnMethodMax": 9,
        "externals": [
            "OCP\\App\\IAppManager"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 153,
        "vocabulary": 41,
        "volume": 819.71,
        "difficulty": 11.76,
        "effort": 9637.75,
        "level": 0.09,
        "bugs": 0.27,
        "time": 535,
        "intelligentContent": 69.72,
        "number_operators": 56,
        "number_operands": 97,
        "number_operators_unique": 8,
        "number_operands_unique": 33,
        "cloc": 59,
        "loc": 130,
        "lloc": 71,
        "mi": 80.28,
        "mIwoC": 37.06,
        "commentWeight": 43.21,
        "kanDefect": 1.17,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.42,
        "relativeSystemComplexity": 11.42,
        "totalStructuralComplexity": 54,
        "totalDataComplexity": 14.5,
        "totalSystemComplexity": 68.5,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenSetPreviewService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResolvedColors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseCssVars",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseMappings",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resolveVarReference",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 17,
        "ccn": 14,
        "ccnMethodMax": 5,
        "externals": [
            "OCP\\App\\IAppManager",
            "OCA\\NLDesign\\Service\\TokenRegistry"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 160,
        "vocabulary": 38,
        "volume": 839.67,
        "difficulty": 9.75,
        "effort": 8186.77,
        "level": 0.1,
        "bugs": 0.28,
        "time": 455,
        "intelligentContent": 86.12,
        "number_operators": 56,
        "number_operands": 104,
        "number_operators_unique": 6,
        "number_operands_unique": 32,
        "cloc": 76,
        "loc": 154,
        "lloc": 78,
        "mi": 80.66,
        "mIwoC": 36.37,
        "commentWeight": 44.29,
        "kanDefect": 1.47,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.87,
        "relativeSystemComplexity": 26.87,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 9.33,
        "totalSystemComplexity": 134.33,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\CustomOverridesService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFilePath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureExists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "read",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "writeFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildCss",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseDeclarations",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRawContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 8,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 22,
        "ccn": 15,
        "ccnMethodMax": 4,
        "externals": [
            "OCP\\App\\IAppManager",
            "OCA\\NLDesign\\Service\\TokenRegistry",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 191,
        "vocabulary": 47,
        "volume": 1060.93,
        "difficulty": 8.41,
        "effort": 8927.31,
        "level": 0.12,
        "bugs": 0.35,
        "time": 496,
        "intelligentContent": 126.08,
        "number_operators": 76,
        "number_operands": 115,
        "number_operators_unique": 6,
        "number_operands_unique": 41,
        "cloc": 98,
        "loc": 194,
        "lloc": 98,
        "mi": 77.94,
        "mIwoC": 33.36,
        "commentWeight": 44.58,
        "kanDefect": 1.61,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.65,
        "relativeSystemComplexity": 37.65,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 14.86,
        "totalSystemComplexity": 338.86,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Service\\TokenRegistry",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTokens",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTabLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokenNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEditable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTokensByTab",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 397,
        "vocabulary": 125,
        "volume": 2765.42,
        "difficulty": 3.17,
        "effort": 8768.39,
        "level": 0.32,
        "bugs": 0.92,
        "time": 487,
        "intelligentContent": 872.17,
        "number_operators": 7,
        "number_operands": 390,
        "number_operators_unique": 2,
        "number_operands_unique": 123,
        "cloc": 54,
        "loc": 136,
        "lloc": 82,
        "mi": 75.3,
        "mIwoC": 33.88,
        "commentWeight": 41.42,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.6,
        "relativeSystemComplexity": 3.6,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 13,
        "totalSystemComplexity": 18,
        "package": "OCA\\NLDesign\\Service\\",
        "pageRank": 0.37,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "OCA\\NLDesign\\Settings\\Admin",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Settings\\ISettings",
            "OCP\\IConfig",
            "OCP\\IL10N",
            "OCP\\AppFramework\\Http\\TemplateResponse",
            "OCP\\AppFramework\\Http\\TemplateResponse"
        ],
        "parents": [],
        "implements": [
            "OCP\\Settings\\ISettings"
        ],
        "lcom": 3,
        "length": 73,
        "vocabulary": 35,
        "volume": 374.44,
        "difficulty": 2.91,
        "effort": 1088.21,
        "level": 0.34,
        "bugs": 0.12,
        "time": 60,
        "intelligentContent": 128.84,
        "number_operators": 11,
        "number_operands": 62,
        "number_operators_unique": 3,
        "number_operands_unique": 32,
        "cloc": 40,
        "loc": 67,
        "lloc": 27,
        "mi": 97.17,
        "mIwoC": 50.62,
        "commentWeight": 46.55,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 4.67,
        "totalSystemComplexity": 20.67,
        "package": "OCA\\NLDesign\\Settings\\",
        "pageRank": 0.09,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]